### ISSUE TITLE
epic: ef-tests

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/keth#129]
## Why

EF-tests are the only guarantee that an EVM implementation is actually sound.

## What

Make sure we can run the code on the rust VM and add an ef-tests runner in the CI.

## How

```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/keth/issues/802
- [ ] #617
- [ ] https://github.com/kkrt-labs/keth/issues/816
- [ ] https://github.com/kkrt-labs/keth/issues/836
- [ ] dev: run python hints in rust vm
- [ ] dev: add logger with serde
- [ ] dev: diff test eels logs with keth ones
- [ ] bug: fix failing cases
- [ ] https://github.com/kkrt-labs/keth/issues/837
```

**Comment by Eikix** [comment]
@enitrat are you self-assigning because this is your next priority? 
if this is not directly your next task, I suggest to unassign you and simply strategize the ef-test epic monday and see who has bandwidth first
