### ISSUE TITLE
epic: Refacto ported tests with new test runner

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/keth#130]
## Why

Most of the code comes from the previous Kakarot for Starknet implementation with an old version of the test runner.

The CI currently takes 20 minutes to run.

## What

Check all test files and refacto to use the new test runners
- remove the `test_xxx.cairo` file when possible
- fuzz with hypothesis and eels instead of parametrize
- use strong typing

## How

Check all test files and do the above steps for each. Create a sub-issue when starting on a file

- [ ] test_duplication_operations.py
- [ ] test_environmental_information.py
- [ ] test_exchange_operations.py
- [ ] test_memory_operations.py
- [ ] test_push_operations.py
- [ ] test_stop_and_math_operations.py
- [ ] test_datacopy.py
- [ ] test_ec_add.py
- [ ] test_ec_mul.py
- [ ] test_ec_recover.py
- [ ] test_modexp.py
- [ ] test_precompiles.py
- [ ] test_ripemd160.py
- [ ] test_sha256.py
- [ ] test_account.py
- [ ] test_evm.py
- [ ] test_memory.py
- [ ] test_stack.py
- [ ] test_state.py
- [ ] test_array.py
- [ ] test_bytes.py
- [ ] test_dict.py
- [ ] test_transaction.py
- [ ] test_uint256.py
- [ ] test_utils.py
