### ISSUE TITLE
epic: Apply audit results from Kakarot to Keth

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/keth#131]
## Why

This codebase is a copy/paste of Kakarot as of mid septembre. Since then, two audits (C4 and Zellic 2) found issues on it.

## What

List all the findings relevant to this context and copy the implemented patches.

## How

Last Kakarot PR included in this repo is https://github.com/kkrt-labs/kakarot/pull/1395

- Pick the list of findings relevant for this context
- create an issue per finding and a PR to solve it
```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/keth/issues/143
- [ ] https://github.com/kkrt-labs/keth/issues/144
- [ ] https://github.com/kkrt-labs/keth/issues/145
- [ ] https://github.com/kkrt-labs/keth/issues/146
- [ ] https://github.com/kkrt-labs/keth/issues/147
- [ ] https://github.com/kkrt-labs/keth/issues/148
- [ ] https://github.com/kkrt-labs/keth/issues/149
- [ ] https://github.com/kkrt-labs/keth/issues/150
- [ ] https://github.com/kkrt-labs/keth/issues/151
- [ ] https://github.com/kkrt-labs/keth/issues/152
- [ ] https://github.com/kkrt-labs/keth/issues/153
- [ ] https://github.com/kkrt-labs/keth/issues/155
- [ ] https://github.com/kkrt-labs/keth/issues/156
- [ ] https://github.com/kkrt-labs/keth/issues/157
- [ ] https://github.com/kkrt-labs/keth/issues/158
- [ ] https://github.com/kkrt-labs/keth/issues/160
- [ ] https://github.com/kkrt-labs/keth/issues/161
- [ ] https://github.com/kkrt-labs/keth/issues/162
- [ ] https://github.com/kkrt-labs/keth/issues/163
- [ ] https://github.com/kkrt-labs/keth/issues/165
```
