### ISSUE TITLE
epic: EELS Stack

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/keth#254]
## Why

As part of the migration to strict the EELS port, we need to refine the stack.

## What

Copy the Stack api from `ethereum/cancun/vm/stack.py`

## How

```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/keth/issues/255
- [ ] https://github.com/kkrt-labs/keth/issues/256
- [ ] https://github.com/kkrt-labs/keth/issues/257
- [ ] https://github.com/kkrt-labs/keth/issues/258
```
