### ISSUE TITLE
feat: implement Set[Uint] type

### ISSUE THREAD

**Issue by obatirou** [kkrt-labs/keth#277]
```[tasklist]
### Tasks
- [x] in `ethereum_types.numeric` add a `SetUintStruct` and `SetUint`
- [x] in `args_gen.py`, update `_cairo_struct_to_python_type` with the new type
- [x] in `gen_arg`, update the condition `if arg_type_origin in (dict, ChainMap, abc.Mapping):` to catch also `Set`
- [x] inside the `if`, if it's a set, create a dict from it `arg = {k: True for k in arg}`
- [x] in `serde.py`, in `if get_origin(python_cls) in (Mapping, abc.Mapping):` update to catch `Set` as well
- [x] if `set`, return `set(d.keys())` instead of the full dict
```

```
struct SetUintDictAccess {
    key: Uint,
    prev_value: bool,
    new_value: bool,
}

struct SetUintStruct {
    dict_ptr_start: SetUintDictAccess*,
    dict_ptr: SetUintDictAccess*,
}

struct SetUint {
    value: SetUintStruct*,
}
```
