### ISSUE TITLE
epic: investigate txs of block 21421739

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/keth#284]
See the graph of step usage. Investigate the spikes > 5M

<img width="600" alt="Image" src="https://github.com/user-attachments/assets/120dd416-0c30-4825-86e0-f0c83dac62ed" />

**Comment by ClementWalter** [comment]
The input data for running `test_eth_block`. To replay one single tx:
- [ ] use etherscan / cast to replay the tx and see what's in
- [ ] replay the tx only by slicing the `transactions` object (not exactly the same conditions but let's see if it gives as many steps)
- [ ] if required, run up to the previous state, dump the post state, and run only the selected tx with the given state.

[21421739_long.json](https://github.com/user-attachments/files/18168906/21421739_long.json)

**Comment by Eikix** [comment]
what is the status of this?
