### ISSUE TITLE
epic: State accesses

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/keth#288]
## Why

In the context of Kakarot, we used DictAccess to store accesses to the EVM state. For each new context, we needed to create a whole new dict (new segment, new dict manager). This is highly inefficient as illustrated in the first tx of block ![21421739](https://github.com/user-attachments/assets/10163060-6f3f-45d3-8d42-8f21b6e9ff3e)

## What

Stop to copy segments. We only need to make sure that the values returned in context are
- consistent with a DictAccess => regular dict squashing
- consistent with the previous (main) state => the prev values of this small segments needs to be consistent with the values from the main segment.

## How

When creating a new context
- create a new segment
- at the end of the context
    - if it reverts, squash and append all the prev keys to the main dict segment
    - if it succeeds, memcpy to the main segment OR squash and append memcpy the squashed dict
```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/keth/issues/359
- [ ] https://github.com/kkrt-labs/keth/issues/360
- [ ] https://github.com/kkrt-labs/keth/issues/361
- [ ] https://github.com/kkrt-labs/keth/issues/403
- [ ] https://github.com/kkrt-labs/keth/issues/404
```
