### ISSUE TITLE
dev: move python hints to a dedicate module

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/keth#290]
## Why

Currently, python hint implementation are just python code in a plain text variable. This prevents benefitting from all the features required when developing (IDE, testing).

## What

Create a hint module where each function is actually a hint.
Use import_lib and inspect to get the body of each function as a hint registered with the function name
```[tasklist]
### Tasks
- [ ] put the hints in `hints.py` next to `compiler.py`
- [ ] rewrite the existing hints in `cairo/src/utils/compiler.py` as proper functions of variables
- [ ] in `implement_hints`, use inspect to get the body of the function
```

``` 
            exec_locals["memory"] = memory = self.validated_memory
            exec_locals["ap"] = ap = self.run_context.ap
            exec_locals["fp"] = fp = self.run_context.fp
            exec_locals["pc"] = pc = self.run_context.pc
            exec_locals["current_step"] = self.current_step
            exec_locals["ids"] = hint.consts(pc, ap, fp, memory)

            exec_locals["vm_load_program"] = self.load_program
            exec_locals["vm_enter_scope"] = self.enter_scope
            exec_locals["vm_exit_scope"] = self.exit_scope
            exec_locals.update(self.static_locals)
            exec_locals["builtin_runners"] = self.builtin_runners
            exec_locals.update(self.builtin_runners)
```

```
CairoHint(
    accessible_scopes=hint_.accessible_scopes,
    flow_tracking_data=hint_.flow_tracking_data,
    code=inspect(hints).get(hint_.code).get_body(),
)
```

**Comment by Eikix** [comment]
Note during tech refinement:
- Part 1 is done in #373 
- Part 2 will be done in sprint 6

**Comment by Eikix** [comment]
Closing this as completed, and opening a follow-up issue
