### ISSUE TITLE
dev: implement Set[Address] type 

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/keth#293]
to prepare for [EVM struct](https://github.com/ethereum/execution-specs/blob/master/src/ethereum/cancun/vm/__init__.py#L79), implement the `Set[Address]` type for key [`account_to_delete`](https://github.com/ethereum/execution-specs/blob/master/src/ethereum/cancun/vm/__init__.py#L94)

```[tasklist]
### Tasks
- [x] create SetAddress struct in `fork_types.cairo` next to `Address`
- [x] create case in args_gen.py `("ethereum", "cancun", "fork_types", "SetAddress"): Set[Address],`
- [x] create test case in `test_serde.py`
```
