### ISSUE TITLE
epic: improve test runner

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/keth#295]
```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/keth/issues/320
- [ ] https://github.com/kkrt-labs/keth/issues/332
- [ ] feat: push tests results in the CI as artifacts to be able to pull them locally
- [ ] feat: don't skip but fast return test result
- [ ] feat: catch errors in the `pytest_collection_modifyitems` to avoid error at the collection level
- [ ] https://github.com/kkrt-labs/keth/issues/344
```

**Comment by Eikix** [comment]
what is the status of this @ClementWalter

**Comment by Eikix** [comment]
closing as completed for sub-items
other non completed items are not planned
