### ISSUE TITLE
epic: fix failing tests in nightly

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/keth#318]
## What

See failing test of https://github.com/kkrt-labs/keth/actions/runs/12526214515/job/34938536446

Also limit number of example or strategies for the very long ones
```[tasklist]
### Tasks
- [x] fix CI job (see the main python) = remove the cairo part in the pytest-version file
- [x] rerun locally all failed test to validate they are still failing
- [x] for the failing tests, create issues in this epic card
- [ ] trigger manually a nightly run and check that it's green
```

**Comment by obatirou** [comment]
Nightly is failing due to being too long:  The timeout-minutes option is not taken into account, it is canceled after 6H by github as the github hosted runners are hosted. 
To have more running time (5 days) and use the timeout-minutes option, self hosted runner need to be used.

* https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
* https://docs.github.com/en/actions/administering-github-actions/usage-limits-billing-and-administration#usage-limits
* https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners#usage-limits

**Comment by ClementWalter** [comment]
@nmvalera is this something we could consider?
