### ISSUE TITLE
epic: log transaction hashes from Exex using the Cairo vm

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/keth#7]
```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/keth/issues/8
- [ ] https://github.com/kkrt-labs/keth/issues/9
- [ ] https://github.com/kkrt-labs/keth/issues/10
```
